### ISSUE TITLE
Backend Problems

### ISSUE THREAD

**Issue by Janninanni3011** [jas3333/GPT-Chat#1]
When I try to run the backend server I got this error:

`C:\Users\Jannik\Desktop\GPT-Chat\backend>node server.js
(node:2736) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server listening on port: 5001
C:\Users\Jannik\Desktop\GPT-Chat\backend\node_modules\mongoose\lib\connection.js:695
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at Connection.openUri (C:\Users\Jannik\Desktop\GPT-Chat\backend\node_modules\mongoose\lib\connection.js:695:11)
    at C:\Users\Jannik\Desktop\GPT-Chat\backend\node_modules\mongoose\lib\index.js:417:10
    at C:\Users\Jannik\Desktop\GPT-Chat\backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Jannik\Desktop\GPT-Chat\backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (C:\Users\Jannik\Desktop\GPT-Chat\backend\node_modules\mongoose\lib\index.js:1270:10)
    at Mongoose.connect (C:\Users\Jannik\Desktop\GPT-Chat\backend\node_modules\mongoose\lib\index.js:416:20)
    at file:///C:/Users/Jannik/Desktop/GPT-Chat/backend/server.js:9:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)

Node.js v18.12.1`

Do you know how to fix this? I wanted to try out GPT-Chat because i hate it when my conversations get deleted when I accidentally reload the page.

**Comment by jas3333** [comment]
In the server.js file found in the backend directory, you need to change the mongoose.connect to your own connection string.
If you have mongodb installed on your system it would look something like this.
```js
mongoose.connect('mongodb://localhost:27017/GPTConversations');
```
If you don't have mongodb running on your system, there is a free online solution. You can try Net Ninjas Mongodb tutorial to set it up. https://www.youtube.com/watch?v=s0anSjEeua8
