### ISSUE TITLE
GPT whants to send image but cant

### ISSUE THREAD

**Issue by Janninanni3011** [jas3333/GPT-Chat#2]
![grafik](https://user-images.githubusercontent.com/107206171/213266538-baf49fbc-7f86-4fd0-965a-e1c60b72a1f4.png)
![grafik](https://user-images.githubusercontent.com/107206171/213266596-b5878cd0-6d5d-4aab-8c61-50b2522f896d.png)
![grafik](https://user-images.githubusercontent.com/107206171/213266624-9763e755-dfc4-45c2-9fc7-abf518018134.png)
![grafik](https://user-images.githubusercontent.com/107206171/213266682-99b56238-7d3b-45d5-a4e9-640bf21d4438.png)
GPT thinks the links are correct but they just return "Image not found" or something like that. Is there any other way GPT could send images? Thanks for your help!

**Comment by jas3333** [comment]
GPT can't send images and will make stuff up when it doesn't know what to say. It's just how completion models work.
